export const TEXT_CONTENT = {
  'global': {
    siteName: 'Whydog',
    siteTitle: 'Whydog - {0}',
    defaultUsername: 'Anonymous',
  },
  'console': {
    title: 'Console {0}',
    placeholder: "Feel confused? Type 'help' to get started!",
    welcome: [
      ' ',
      '  @#FFF700██╗    ██╗██╗  ██╗██╗   ██╗██████╗  ██████╗  ██████╗',
      '  @#FFF700██║    ██║██║  ██║╚██╗ ██╔╝██╔══██╗██╔═══██╗██╔════╝',
      '  @#FFF700██║ █╗ ██║███████║ ╚████╔╝ ██║  ██║██║   ██║██║  ███╗',
      '  @#FFF700██║███╗██║██╔══██║  ╚██╔╝  ██║  ██║██║   ██║██║   ██║',
      '  @#FFF700╚███╔███╔╝██║  ██║   ██║   ██████╔╝╚██████╔╝╚██████╔╝',
      '  @#FFF700 ╚══╝╚══╝ ╚═╝  ╚═╝   ╚═╝   ╚═════╝  ╚═════╝  ╚═════╝',
      ' ',
      "  @#bababaWhydog's Playground — Personal Terminal v1.0",
      '  @#bababa─────────────────────────────────────────────',
      ' ',
      '  @#FF77B7Quick Start:@#',
      '    @#00ffaahelp@#            List all available commands',
      '    @#00ffaacd@# @#FFF700<path>@#       Navigate to a different page',
      '    @#00ffaals@#              List available paths',
      '    @#00ffaacl@#              Clear console output',
      ' ',
      '  @#FF77B7Shortcuts:@#',
      '    @#FFF700Ctrl + `@#        Toggle console window',
      '    @#FFF700Esc@#             Restore last minimized console',
      '    @#FFF700Tab@#             Auto-complete commands',
      '    @#FFF700↑ / ↓@#           Browse command history',
      ' ',
      '  @#f9f284Ready. Type a command to get started.',
      ' ',
    ],
  },
  'commands': {
    commandNotFound: 'Unknown command: @#fff700{0}@#. Type @#00ffaahelp@# to see available commands.',
    availableCommands: 'Available commands:',
    separator: '---',
    availablePaths: 'Available paths:',
    help: {
      usage: '{0} — {1}',
    },
    background: {
      reset: 'Background image has been reset.',
      urlInvalid: 'Invalid URL. Usage: @#00ffaabackground@# @#fff700<image_url>@#',
      set: 'Background image set to @#fff700{0}@#',
    },
    backgroundcolor: {
      reset: 'Background color has been reset.',
      colorInvalid: 'Invalid color. Must be a hex code (e.g. #FF0000). Usage: @#00ffaabackgroundcolor@# @#fff700<#hex>@#',
      set: 'Background color set to @#fff700{0}@#',
    },
    username: {
      usage: 'Usage: @#00ffaausername@# @#fff700<name>@#',
      tooLong: 'Name too long — max 20 characters.',
      set: 'Username changed to @#fff700{0}@#',
    },
    settings: {
      opened: 'Settings panel opened.',
      closed: 'Settings panel closed.',
    },
    music: {
      usage: 'Usage: @#00ffaamusic@# @#fff700[-p | -s | -i | -l]@#',
      list: 'Music list:',
      nowPlaying: 'Now playing: @#FFF700{0}@#...',
    },
    download: {
      usage: 'Usage: @#00ffaadownload@# @#fff700<video_url>@# @#fff700[-v | -a]@#',
      invalidUrl: 'Invalid video URL.',
      pending: 'Preparing download: @#fff700{0}@# ({1})',
      starting: 'Download started...',
      error: {
        downloadVideoFailed: 'Video download failed: {0}',
        downloadAudioFailed: 'Audio download failed: {0}',
      },
    },
  },
  'home': {
    commands: {
      github: 'Opening @#FFF700GitHub@# profile...',
      youtube: 'Opening @#FFF700YouTube@# channel...',
      twitter: 'Opening @#FFF700Twitter@# profile...',
      instagram: 'Opening @#FFF700Instagram@# profile...',
      twitch: 'Opening @#FFF700Twitch@# channel...',
      discord: 'Opening @#FFF700Discord@# profile...',
      email: 'Opening email client...',
      osu: 'Opening @#FFF700osu!@# profile...',
    },
  },
  'listentogether': {
    unmute: '點我一下',
    commands: {
      send: {
        usage: 'Usage: @#00ffaasend@# @#fff700<message>@#',
      },
      queue: {
        usage: 'Usage: @#00ffaaqueue@# @#fff700<video_url | playlist_url>@#',
        cannotPlay: 'Unsupported URL — cannot play this link.',
        addedTracks: 'Added @#fff700{0}@# tracks to queue (#{1} ~ #{2})',
        addedTrack: 'Added @#fff700{0}@# to queue (#{1})',
        invalidUrl: 'Invalid URL.',
      },
      remove: {
        usage: 'Usage: @#00ffaaremove@# @#fff700<index | *>@#',
        removedAll: 'All tracks removed from the queue.',
        invalidIndex: 'Invalid index.',
        indexOutOfRange: 'Index out of range.',
        removed: 'Removed track #{0} from the queue.',
      },
      play: {
        start: 'Resuming playback...',
      },
      pause: {
        pause: 'Playback paused.',
      },
      switch: {
        usage: 'Usage: @#00ffaaswitch@# @#fff700<index> | -n | -p@#',
        next: 'Switched to the next track.',
        prev: 'Switched to the previous track.',
        invalidIndex: 'Invalid index.',
        indexOutOfRange: 'Index out of range.',
        switchTo: 'Switched to track #{0}.',
      },
      volume: {
        usage: 'Usage: @#00ffaavolume@# @#fff700<0–100>@#',
        invalid: 'Invalid volume value.',
        set: 'Volume set to @#fff700{0}@#',
      },
      loop: {
        usage: 'Usage: @#00ffaaloop@# @#fff700[-t | -f]@#',
        on: 'Loop enabled.',
        off: 'Loop disabled.',
      },
      random: {
        usage: 'Usage: @#00ffaarandom@# @#fff700[-t | -f]@#',
        on: 'Shuffle enabled.',
        off: 'Shuffle disabled.',
      },
      rate: {
        usage: 'Usage: @#00ffaarate@# @#fff700<percent>@#',
        invalid: 'Invalid rate value.',
        set: 'Playback speed set to @#fff700{0}%@#',
      },
      seek: {
        usage: 'Usage: @#00ffaaseek@# @#fff700<seconds>@#',
        invalid: 'Invalid time value.',
        outOfRange: 'Time out of range.',
        seekTo: 'Seeked to @#fff700{0}s@#',
      },
      refresh: {
        message: 'Player state refreshed.',
      },
      playlist: {
        detail: 'Playlist (detailed):',
        list: 'Playlist:',
      },
      vibe: {
        usage: 'Usage: @#00ffaavibe@# @#fff700<default | lofi | rave | cinema | dawn>@#',
        invalid: 'Invalid vibe. Choose: @#fff700default | lofi | rave | cinema | dawn@#',
        set: 'Vibe set to @#fff700{0}@#',
      },
    },
    logs: {
      addedTracks: '{0} 在播放清單中新增了 {1} 首歌曲 (#{2} ~ #{3})',
      addedTrack: '{0} 在播放清單中新增了 {1} (#{2})',
      removedAll: '{0} 清空了播放清單',
      removedTrack: '{0} 移除了 {1} (#{2})',
      play: '{0} 繼續播放',
      pause: '{0} 暫停播放',
      switchNext: '{0} 切換到下一首',
      switchPrev: '{0} 切換到上一首',
      switchTo: '{0} 切換到 #{1}',
      loopOn: '{0} 開啟循環播放',
      loopOff: '{0} 關閉循環播放',
      randomOn: '{0} 開啟隨機播放',
      randomOff: '{0} 關閉隨機播放',
      rate: '{0} 將播放速度設為 {1}%',
      seek: '{0} 跳轉到 {1} 秒',
      refresh: '{0} 重新同步播放器',
      playlistUpdated: 'Playlist updated:',
      joined: '{0} joined the room',
      vibe: '{0} set the vibe to {1}',
    },
    errors: {
      getVideoInfo: 'Failed to fetch video info: {0}',
      getPlaylist: 'Failed to fetch playlist info: {0}',
      connectError: 'Server connection failed (id: {0})',
      serverError: 'Server error: {0}',
      disconnect: 'Disconnected from server.',
      playerError: 'Player error: {0}',
    },
  },
  'blogPost': {
    loading: 'Loading post...',
    notFound: 'Post not found.',
    backLink: '\u2190 Back to ~/blog',
  },
  '/': {
    title: 'Personal site',
    subtitle: "I'm Whydog, a 18yo developer passionate about full-stack development, UI/UX design.",
    about: [
      '@#FFF700Whitedog@#@@#00f3ffNTUST-CSIE@#, Taiwan',
      '(18yo) (a.k.a. Whydog)',
      'I @#FF77B7love@# @#00ffaaplaying games@# and @#00ffaacoding@#. Sometimes @#00ffaawatching anime@#.',
      'I @#FF77B7want@# to be a @#00ffaafull-stack@# developer, as well as a @#00ffaaUI/UX@# designer.',
      "This website is built with @#00ffaaReact@#, and I'm still working on it.",
      '@#f9f284Hope you enjoy your stay here.',
    ],
    social: [
      {
        icon: 'gmail',
        value: 'joshhuang9508@gmail.com — Type @#FFF700email@# to send me an email',
      },
      {
        icon: 'twitter',
        value: '@whydog5555 — Type @#FFF700twitter@# to open my Twitter profile',
      },
      {
        icon: 'instagram',
        value: '@whydog5555 — Type @#FFF700instagram@# to open my Instagram profile',
      },
      {
        icon: 'github',
        value: 'Joshhuang9508 — Type @#FFF700github@# to open my GitHub profile',
      },
      {
        icon: 'youtube',
        value: 'Whydog — Type @#FFF700youtube@# to open my YouTube channel',
      },
      {
        icon: 'twitch',
        value: 'whydog5555 — Type @#FFF700twitch@# to open my Twitch channel',
      },
      {
        icon: 'discord',
        value: '@whydog — Type @#FFF700discord@# to open my Discord profile',
      },
      {
        icon: 'osu',
        value: '-Whitedog- — Type @#FFF700osu@# to open my osu! profile',
      },
    ],
    hero: {
      name: 'Whitedog',
      school: 'NTUST-CSIE',
      age: '18yo',
      bio: '\"The goal of life is to achieve @#00ffaagentleness@#\"',
    },
    sections: {
      aboutMe: '@#fff700ABOUT ME@#',
      latestPost: '@#ffa24cLATEST POST@#',
      projects: '@#00ffaaPROJECTS@#',
      osuStats: '@#ff77b7OSU! STATS@#',
      aboutSite: '@#fff700ABOUT THIS SITE@#',
    },
    latestPost: {
      allPosts: 'All Posts \u2192',
      comingSoon: 'Coming soon...',
      stayTuned: 'Stay tuned for the first blog post.',
    },
    projects: {
      viewAll: 'View All \u2192',
      noImage: 'No image',
    },
    osu: {
      details: 'Details \u2192',
      globalRank: 'Global Rank',
      pp: 'PP',
      accuracy: 'Accuracy',
    },
    features: {
      terminal: {
        title: '@#00ffaa>_@# Built-in Terminal',
        desc: 'This site comes with a draggable, resizable console — a real terminal you can use to navigate pages, open links, and explore hidden commands. Try it out!',
        ctrl: 'Ctrl',
        backtick: '`',
        esc: 'Esc',
        tab: 'Tab',
        toggleConsole: 'Toggle console',
        minimize: 'Minimize',
        autocomplete: 'Autocomplete',
      },
      commands: {
        title: '@#ffa24c$@# Quick Commands',
        desc: 'Type @#fff700help@# to see all available commands. Use @#fff700cd@# to navigate between pages, or @#fff700github@#, @#fff700osu@#, @#fff700music -i@# to interact directly.',
      },
    },
    footer: 'built with next.js + too much coffee',
  },
  '/listentogether': {
    title: 'Listen Together',
    subtitle: 'A web-based music sync player. Listen to music with your friends in real-time.',
  },
  '/projects': {
    title: 'Projects',
    subtitle: 'My open-source work and side projects.',
    noImages: 'No images yet',
    commands: {
      open: {
        usage: 'Usage: @#00ffaaopen@# @#fff700<project-name>@#',
        opening: 'Opening @#fff700{0}@#...',
        notFound: 'Project @#fff700{0}@# not found.',
      },
    },
  },
  '/osu': {
    title: 'My osu! Stats',
    subtitle: 'My osu! profile and gameplay statistics.',
    loading: 'Loading stats...',
    unavailable: {
      title: 'Stats temporarily unavailable.',
      desc: 'osu! API proxy not configured yet.',
    },
    labels: {
      globalRank: 'Global Rank',
      country: 'Country',
      pp: 'PP',
      accuracy: 'Accuracy',
      playCount: 'Play Count',
      playTime: 'Play Time',
      gradeDistribution: 'Grade Distribution',
    },
    commands: {
      stats: {
        notAvailable: 'osu! stats not available.',
        header: '@#ff77b7osu! Stats for {0}@#',
        globalRank: 'Global Rank: @#fff700#{0}@#',
        countryRank: 'Country Rank: @#00ffaa#{0}@#',
        pp: 'PP: @#ffa24c{0}@#',
        accuracy: 'Accuracy: @#fff{0}@#',
        playCount: 'Play Count: {0}',
        playTime: 'Play Time: {0}',
      },
    },
  },
  '/blog': {
    title: 'My Blog',
    subtitle: 'Thoughts on development, life, and gaming.',
    loading: 'Loading posts...',
    empty: 'No posts yet. Stay tuned.',
    commands: {
      read: {
        usage: 'Usage: @#00ffaaread@# @#fff700<slug>@#',
        opening: 'Opening @#fff700{0}@#...',
        notFound: 'Post @#fff700{0}@# not found.',
      },
    },
  },
  '*': {
    title: 'Oops!',
    subtitle: 'Page not found!',
    error: "@#FF77B7Error:@# This page doesn't exist. Type @#00ffaa'cd'@# to go back to the home page.",
  },
};
