export const TEXT_CONTENT = {
  'terminal': {
    title: 'Terminal {0}',
    placeholder: "Feel confused? Type 'help' to get started!",
    welcome: [
      ' ',
      '  @#FFF700██╗    ██╗██╗  ██╗██╗   ██╗██████╗  ██████╗  ██████╗',
      '  @#FFF700██║    ██║██║  ██║╚██╗ ██╔╝██╔══██╗██╔═══██╗██╔════╝',
      '  @#FFF700██║ █╗ ██║███████║ ╚████╔╝ ██║  ██║██║   ██║██║  ███╗',
      '  @#FFF700██║███╗██║██╔══██║  ╚██╔╝  ██║  ██║██║   ██║██║   ██║',
      '  @#FFF700╚███╔███╔╝██║  ██║   ██║   ██████╔╝╚██████╔╝╚██████╔╝',
      '  @#FFF700 ╚══╝╚══╝ ╚═╝  ╚═╝   ╚═╝   ╚═════╝  ╚═════╝  ╚═════╝',
      ' ',
      "  @#bababaWhydog's Playground — Personal Terminal v1.0",
      '  @#bababa─────────────────────────────────────────────',
      ' ',
      '  @#FF77B7Quick Start:@#',
      '    @#00ffaahelp@#            List all available commands',
      '    @#00ffaacd@# @#FFF700<path>@#       Navigate to a different page',
      '    @#00ffaals@#              List available paths',
      '    @#00ffaacl@#              Clear terminal output',
      ' ',
      '  @#FF77B7Shortcuts:@#',
      '    @#FFF700Ctrl + `@#        Toggle terminal window',
      '    @#FFF700Esc@#             Restore last minimized terminal',
      '    @#FFF700Tab@#             Auto-complete commands',
      '    @#FFF700↑ / ↓@#           Browse command history',
      ' ',
      '  @#f9f284Ready. Type a command to get started.',
      ' ',
    ],
    commandNotFound: 'Unknown command: @#fff700{0}@#. Type @#00ffaahelp@# to see available commands.',
  },
  'settings': {
    tip: '// tip: type @#fff700theme --help@# in terminal for CLI access',
    background: {
      title: 'background',
      image: 'Image',
      overlay: 'Overlay',
    },
    theme: {
      title: 'theme',
      cardColorHint: '// drives @#fff700--card-color@#',
      cardColor: 'Card Color',
      textHighlightHint: '// drives @#fff700--text-highlight@#',
      textHighlight: 'Text Highlight',
    },
    text: {
      title: 'text',
      primary: 'primary',
      secondary: 'secondary',
      muted: 'muted',
    },
    accent: {
      title: 'accent',
      add: '+ push',
    },
    reset: 'reset --all',
    exit: 'exit',
  },
  'global': {
    commands: {
      help: {
        description: 'List all available commands',
        commandUsage: '{0} — {1}',
        availableCommands: 'Available commands:',
        separator: '---',
      },
      username: {
        description: 'Change your display name (max 20 chars)',
        usage: '@#00ffaausername@# @#fff700<name>@#',
        tooLong: 'Name too long — max 20 characters.',
        set: 'Username changed to @#fff700{0}@#',
      },
      settings: {
        description: 'Open or close the settings panel',
        usage: '@#00ffaasettings@# @#fff700[-c]@#',
        opened: 'Settings panel opened.',
        closed: 'Settings panel closed.',
      },
      theme: {
        description: 'Manage theme settings',
        usage: '@#00ffaatheme@# @#fff700<sub>@# @#fff700[args]@# (try @#fff700theme -h@#)',
        help: [
          '@#fff700theme@# — manage theme settings',
          '  @#00ffaatheme@#                                show current theme',
          '  @#00ffaatheme@# @#fff700-h@#                             show this help',
          '  @#00ffaatheme reset@#                          reset to defaults',
          '  @#00ffaatheme bg-image@# @#fff700<url|-r>@#              set or reset background image',
          '  @#00ffaatheme bg@# @#fff700<h> <s> <l> [a]@#               set background overlay HSL(A)',
          '  @#00ffaatheme color@# @#fff700<h> <s> <l>@#                set theme color (card + highlight)',
          '  @#00ffaatheme blur@# @#fff700<px>@#                       set card blur radius',
          '  @#00ffaatheme text-highlight@# @#fff700<h> <s> <l>@#      set text highlight HSL',
          '  @#00ffaatheme text@# @#fff700<primary|secondary|muted> <#hex>@#',
          '  @#00ffaatheme accent add@# @#fff700<#hex>@#                push accent color',
          '  @#00ffaatheme accent rm@# @#fff700<index>@#                remove accent at index',
          '  @#00ffaatheme accent set@# @#fff700<index> <#hex>@#        set accent at index',
        ],
        show: [
          '@#fff700current theme:@#',
          '  bg-image    = @#fff700{0}@#',
          '  bg (h s l/a)= @#fff700{1}@#',
          '  color (hsl) = @#fff700{2}@#',
          '  blur        = @#fff700{3}@#',
          '  text.highlight = @#fff700{4}@#',
          '  text.primary   = @#fff700{5}@#',
          '  text.secondary = @#fff700{6}@#',
          '  text.muted     = @#fff700{7}@#',
          '  accent[]    = @#fff700{8}@#',
        ],
        reset: 'Theme reset to defaults.',
        bgImageSet: 'Background image set to @#fff700{0}@#',
        bgImageReset: 'Background image reset.',
        bgSet: 'Background overlay set: @#fff700{0}@#',
        colorSet: 'Theme color set: @#fff700hsl({0})@#',
        blurSet: 'Card blur set to @#fff700{0}px@#',
        blurInvalid: 'Invalid blur value. Use a non-negative number.',
        textKey: 'Invalid text key. Use @#fff700primary@#, @#fff700secondary@# or @#fff700muted@#.',
        textSet: 'text.@#fff700{0}@# = @#fff700{1}@#',
        hslInvalid: 'Invalid HSL. @#fff700<h 0-360> <s 0-100> <l 0-100> [a 0-1]@#',
        hexInvalid: 'Invalid hex color. Expected format @#fff700#rrggbb@#',
        accent: '@#00ffaatheme accent@# @#fff700<add|rm|set>@# ...',
        accentAdded: 'Accent @#fff700{0}@# pushed at index @#fff700{1}@#',
        accentRemoved: 'Accent at index @#fff700{0}@# removed.',
        accentSet: 'accent[@#fff700{0}@#] = @#fff700{1}@#',
        accentIndexInvalid: 'Invalid accent index.',
        unknownSub: 'Unknown subcommand: @#fff700{0}@#',
      },
      music: {
        description: 'Manage music playback',
        usage: '@#00ffaamusic@# @#fff700[-p|-s|-i|-l]@#',
        list: 'Music list:',
        nowPlaying: 'Now playing: @#FFF700{0}@#...',
      },
      download: {
        description: 'Download a video or audio from a URL',
        usage: '@#00ffaadownload@# @#fff700<video_url>@# @#fff700[-v|-a]@#',
        invalidUrl: 'Invalid video URL.',
        pending: 'Preparing download: @#fff700{0}@# ({1})',
        starting: 'Download started...',
        error: {
          downloadVideoFailed: 'Video download failed: {0}',
          downloadAudioFailed: 'Audio download failed: {0}',
        },
      },
    },
  },
  'home': {
    commands: {
      open: {
        description: 'Open a page',
        usage: '@#00ffaaopen@# @#fff700<page_name>@#',
        github: 'Opening @#FFF700GitHub@# profile...',
        youtube: 'Opening @#FFF700YouTube@# channel...',
        twitter: 'Opening @#FFF700Twitter@# profile...',
        instagram: 'Opening @#FFF700Instagram@# profile...',
        twitch: 'Opening @#FFF700Twitch@# channel...',
        discord: 'Opening @#FFF700Discord@# profile...',
        email: 'Opening email client...',
        osu: 'Opening @#FFF700osu!@# profile...',
      },
    },
    about: [
      '@#FFF700Whitedog@#@@#00f3ffNTUST-CSIE@#, Taiwan',
      '(18yo) (a.k.a. Whydog)',
      'I @#FF77B7love@# @#00ffaaplaying games@# and @#00ffaacoding@#. Sometimes @#00ffaawatching anime@#.',
      'I @#FF77B7want@# to be a @#00ffaafull-stack@# developer, as well as a @#00ffaaUI/UX@# designer.',
      "This website is built with @#00ffaaReact@#, and I'm still working on it.",
      '@#f9f284Hope you enjoy your stay here.',
    ],
    social: [
      {
        icon: 'gmail',
        value: 'joshhuang9508@gmail.com — Type @#FFF700email@# to send me an email',
      },
      {
        icon: 'twitter',
        value: '@whydog5555 — Type @#FFF700twitter@# to open my Twitter profile',
      },
      {
        icon: 'instagram',
        value: '@whydog5555 — Type @#FFF700instagram@# to open my Instagram profile',
      },
      {
        icon: 'github',
        value: 'Joshhuang9508 — Type @#FFF700github@# to open my GitHub profile',
      },
      {
        icon: 'youtube',
        value: 'Whydog — Type @#FFF700youtube@# to open my YouTube channel',
      },
      {
        icon: 'twitch',
        value: 'whydog5555 — Type @#FFF700twitch@# to open my Twitch channel',
      },
      {
        icon: 'discord',
        value: '@whydog — Type @#FFF700discord@# to open my Discord profile',
      },
      {
        icon: 'osu',
        value: '-Whitedog- — Type @#FFF700osu@# to open my osu! profile',
      },
    ],
    hero: {
      name: 'Whitedog',
      school: 'NTUST-CSIE',
      age: '18yo',
      bio: '\"The goal of life is to achieve @#00ffaagentleness@#\"',
    },
    sections: {
      aboutMe: 'ABOUT ME',
      latestPost: '@#ffa24cLATEST POST@#',
      projects: '@#00ffaaPROJECTS@#',
      osuStats: '@#ff77b7OSU! STATS@#',
      aboutSite: 'ABOUT THIS SITE',
    },
    latestPost: {
      allPosts: 'All Posts \u2192',
      comingSoon: 'Coming soon...',
      stayTuned: 'Stay tuned for the first blog post.',
    },
    projects: {
      viewAll: 'View All \u2192',
      noImage: 'No image',
    },
    osu: {
      details: 'Details \u2192',
      globalRank: 'Global Rank',
      pp: 'PP',
      accuracy: 'Accuracy',
    },
    features: {
      terminal: {
        title: '@#00ffaa>_@# Built-in Terminal',
        desc: 'This site comes with a draggable, resizable terminal — a real terminal you can use to navigate pages, open links, and explore hidden commands. Try it out!',
        ctrl: 'Ctrl',
        backtick: '`',
        esc: 'Esc',
        tab: 'Tab',
        toggleTerminal: 'Toggle terminal',
        minimize: 'Minimize',
        autocomplete: 'Autocomplete',
      },
      commands: {
        title: '@#ffa24c$@# Quick Commands',
        desc: 'Type @#fff700help@# to see all available commands. Use @#fff700cd@# to navigate between pages, or @#fff700github@#, @#fff700osu@#, @#fff700music -i@# to interact directly.',
      },
    },
    footer: 'built with next.js + too much coffee',
  },
  'listentogether': {
    unmute: '點我一下',
    commands: {
      send: {
        description: 'Send a message to the room',
        usage: '@#00ffaasend@# @#fff700<message>@#',
      },
      queue: {
        description: 'Add a YouTube video or playlist to the queue',
        usage: '@#00ffaaqueue@# @#fff700<video_url|-playlist_url>@#',
        cannotPlay: 'Unsupported URL — cannot play this link.',
        addedTracks: 'Added @#fff700{0}@# tracks to queue (#{1} ~ #{2})',
        addedTrack: 'Added @#fff700{0}@# to queue (#{1})',
        invalidUrl: 'Invalid URL.',
      },
      remove: {
        description: 'Remove a track from the queue by index (* = all)',
        usage: '@#00ffaaremove@# @#fff700<index|*>@#',
        removedAll: 'All tracks removed from the queue.',
        invalidIndex: 'Invalid index.',
        indexOutOfRange: 'Index out of range.',
        removed: 'Removed track #{0} from the queue.',
      },
      play: {
        description: 'Start or resume playback',
        usage: '@#00ffaaplay@#',
        start: 'Resuming playback...',
      },
      pause: {
        description: 'Pause playback',
        usage: '@#00ffaapause@#',
        pause: 'Playback paused.',
      },
      switch: {
        description: 'Switch to a different track',
        usage: '@#00ffaaswitch@# @#fff700<index|-n|-p>@#',
        next: 'Switched to the next track.',
        prev: 'Switched to the previous track.',
        invalidIndex: 'Invalid index.',
        indexOutOfRange: 'Index out of range.',
        switchTo: 'Switched to track #{0}.',
      },
      volume: {
        description: 'Set the playback volume (0-100)',
        usage: '@#00ffaavolume@# @#fff700<0–100>@#',
        invalid: 'Invalid volume value.',
        set: 'Volume set to @#fff700{0}@#',
      },
      loop: {
        description: 'Enable or disable loop playback',
        usage: '@#00ffaaloop@# @#fff700[-t|-f]@#',
        on: 'Loop enabled.',
        off: 'Loop disabled.',
      },
      random: {
        description: 'Enable or disable shuffle playback',
        usage: '@#00ffaarandom@# @#fff700[-t|-f]@#',
        on: 'Shuffle enabled.',
        off: 'Shuffle disabled.',
      },
      rate: {
        description: 'Set the playback speed (e.g. 100 = normal)',
        usage: '@#00ffaarate@# @#fff700<percent>@#',
        invalid: 'Invalid rate value.',
        set: 'Playback speed set to @#fff700{0}%@#',
      },
      seek: {
        description: 'Jump to a specific time in seconds',
        usage: '@#00ffaaseek@# @#fff700<seconds>@#',
        invalid: 'Invalid time value.',
        outOfRange: 'Time out of range.',
        seekTo: 'Seeked to @#fff700{0}s@#',
      },
      refresh: {
        description: 'Re-sync the player state from the server',
        usage: '@#00ffaarefresh@#',
        message: 'Player state refreshed.',
      },
      playlist: {
        description: 'Show the current playlist',
        usage: '@#00ffaaplaylist@# @#fff700[-d|-l]@#',
        detail: 'Playlist (detailed):',
        list: 'Playlist:',
      },
      vibe: {
        description: 'Set the ambiance of the room',
        usage: '@#00ffaavibe@# @#fff700<default|-lofi|-rave|-cinema|-dawn>@#',
        invalid: 'Invalid vibe. Choose: @#fff700default|-lofi|-rave|-cinema|-dawn>@#',
        set: 'Vibe set to @#fff700{0}@#',
      },
    },
    logs: {
      addedTracks: '{0} added {1} tracks to the playlist (#{2} ~ #{3})',
      addedTrack: '{0} added {1} track to the playlist (#{2})',
      removedAll: '{0} cleared the playlist',
      removedTrack: '{0} removed {1} track from the playlist (#{2})',
      play: '{0} resumed playback',
      pause: '{0} paused playback',
      switchNext: '{0} switched to the next track',
      switchPrev: '{0} switched to the previous track',
      switchTo: '{0} switched to #{1}',
      loopOn: '{0} enabled loop playback',
      loopOff: '{0} disabled loop playback',
      randomOn: '{0} enabled shuffle playback',
      randomOff: '{0} disabled shuffle playback',
      rate: '{0} set playback speed to {1}%',
      seek: '{0} jumped to {1} seconds',
      refresh: '{0} refreshed player state',
      playlistUpdated: 'Playlist updated:',
      joined: '{0} joined the room',
      vibe: '{0} set the vibe to {1}',
    },
    errors: {
      getVideoInfo: 'Failed to fetch video info: {0}',
      getPlaylist: 'Failed to fetch playlist info: {0}',
      connectError: 'Server connection failed (id: {0})',
      serverError: 'Server error: {0}',
      disconnect: 'Disconnected from server.',
      playerError: 'Player error: {0}',
    },
  },
  'projects': {
    subtitle: 'My open-source work and side projects.',
    noImages: 'No images yet',
    commands: {
      open: {
        description: 'Open a project',
        usage: '@#00ffaaopen@# @#fff700<project-name>@#',
        opening: 'Opening @#fff700{0}@#...',
        notFound: 'Project @#fff700{0}@# not found.',
      },
    },
  },
  'osu': {
    loading: 'Loading stats...',
    unavailable: {
      title: 'Stats temporarily unavailable.',
      desc: 'osu! API proxy not configured yet.',
    },
    globalRank: 'Global Rank',
    country: 'Country',
    pp: 'PP',
    accuracy: 'Accuracy',
    playCount: 'Play Count',
    playTime: 'Play Time',
    rankHistory: 'RANK HISTORY',
    monthlyActivity: 'MONTHLY ACTIVITY',
    hitDistribution: 'HIT DISTRIBUTION',
    gradeCounts: 'GRADE COUNTS',
    dailyStreak: 'daily streak',
    bestStreak: 'Best',
    day: '{0}d',
    peakRank: 'PEAK',
    maxCombo: 'MAX COMBO',
    totalHits: 'TOTAL HITS',
    rankedScore: 'RANKED SCORE',
    profilePage: 'PROFILE PAGE',
    commands: {
      stats: {
        notAvailable: 'osu! stats not available.',
        header: '@#ff77b7osu! Stats for {0}@#',
        globalRank: 'Global Rank: @#fff700#{0}@#',
        countryRank: 'Country Rank: @#00ffaa#{0}@#',
        pp: 'PP: @#ffa24c{0}@#',
        accuracy: 'Accuracy: @#ffffff{0}@#',
        playCount: 'Play Count: @#ffffff{0}@#',
        playTime: 'Play Time: @#ffffff{0}@#',
      },
    },
  },
  'blog': {
    subtitle: 'Thoughts on development, life, and gaming.',
    loading: 'Loading posts...',
    empty: 'No posts yet. Stay tuned.',
    readTime: '{0} minutes read',
  },
  'blogPost': {
    loading: 'Loading post...',
    readTime: '{0} minutes read',
    notFound: 'Post not found.',
    backLink: '\u2190 Back to ~/blog',
  },
  'notfound': {
    error: 'Page not found: @#fff700{0}@#',
  },
  '/': {
    title: "Whydog's Playground",
    subtitle: "I'm Whydog, a 18yo developer passionate about full-stack development, UI/UX design.",
  },
  '/listentogether': {
    title: 'Listen Together',
    subtitle: 'A web-based music sync player. Listen to music with your friends in real-time.',
  },
  '/projects': {
    title: 'Projects',
    subtitle: 'My open-source work and side projects.',
  },
  '/osu': {
    title: 'My osu! Stats',
    subtitle: 'My osu! profile and gameplay statistics.',
  },
  '/blog': {
    title: 'Whydog - My Blog',
    subtitle: 'Thoughts on development, life, and gaming.',
  },
  '*': {
    title: 'Whydog - Oops!',
    subtitle: 'Page not found.',
  },
};
